const MOCK_PRODUCTS = [
  { id: 'p1', title: 'Celestial Bloom Gift Box', price: 1499, originalPrice: 1899, category: 'her', occasion: 'birthday', rating: 4.8, reviews: 124, stock: 50, description: 'A luxurious curated box featuring artisan candles, bath salts, and floral teas. Beautifully packaged with hand-tied ribbons — perfect for her special day.', images: ['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=600&auto=format&fit=crop'], tags: ['luxury', 'floral', 'spa'], isNew: true },
  { id: 'p2', title: 'Executive Leather Journal Set', price: 2199, originalPrice: null, category: 'him', occasion: 'corporate', rating: 4.7, reviews: 89, stock: 30, description: 'Premium full-grain leather journal paired with a gold-tipped fountain pen. A sophisticated gift for the modern professional.', images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=600&auto=format&fit=crop'], tags: ['leather', 'premium', 'stationery'], isNew: false },
  { id: 'p3', title: 'Rose Gold Jewellery Keepsake Box', price: 3299, originalPrice: 4199, category: 'her', occasion: 'anniversary', rating: 4.9, reviews: 203, stock: 20, description: 'Handcrafted velvet-lined jewellery box with rose gold hardware. An heirloom-quality gift she will treasure forever.', images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600&auto=format&fit=crop'], tags: ['jewellery', 'rose-gold', 'keepsake'], isNew: true },
  { id: 'p4', title: 'Artisan Whisky & Cigar Gift Set', price: 4599, originalPrice: null, category: 'him', occasion: 'anniversary', rating: 4.6, reviews: 67, stock: 15, description: "A gentleman's indulgence — premium single malt whisky miniatures paired with hand-rolled cigars in a lacquered wooden case.", images: ['https://images.unsplash.com/photo-1569529465841-dfecdab7503b?q=80&w=600&auto=format&fit=crop'], tags: ['whisky', 'luxury', 'premium'], isNew: false },
  { id: 'p5', title: 'Luxury Spa & Wellness Hamper', price: 1899, originalPrice: 2299, category: 'her', occasion: 'birthday', rating: 4.8, reviews: 156, stock: 40, description: 'Transform any bathroom into a sanctuary. Includes bath bombs, essential oils, face masks, and hand cream in a beautiful wicker basket.', images: ['https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=600&auto=format&fit=crop'], tags: ['spa', 'wellness', 'self-care'], isNew: true },
  { id: 'p6', title: "Couple's Memory Jar Kit", price: 899, originalPrice: null, category: 'her', occasion: 'anniversary', rating: 4.5, reviews: 312, stock: 100, description: 'A beautifully decorated glass jar with 52 custom memory prompt cards. Fill it together, open one each week.', images: ['https://images.unsplash.com/photo-1513201099705-a9746e1e201f?q=80&w=600&auto=format&fit=crop'], tags: ['couple', 'memory', 'romantic'], isNew: false },
  { id: 'p7', title: 'Premium Watch Display Box', price: 5499, originalPrice: null, category: 'him', occasion: 'birthday', rating: 4.9, reviews: 45, stock: 10, description: 'Hand-stitched leather watch box with silk inserts. Holds 6 timepieces and arrives with a premium polishing kit.', images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=600&auto=format&fit=crop'], tags: ['watches', 'leather', 'premium'], isNew: true },
  { id: 'p8', title: 'Wedding Blessing Hamper', price: 3499, originalPrice: 4299, category: 'her', occasion: 'wedding', rating: 4.7, reviews: 98, stock: 25, description: 'A curated basket of artisan sweets, champagne truffles, and a personalised wedding card. Wrapped in gold organza ribbon.', images: ['https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=600&auto=format&fit=crop'], tags: ['wedding', 'hamper', 'sweets'], isNew: false },
  { id: 'p9', title: 'Tech Enthusiast Gift Box', price: 2799, originalPrice: null, category: 'him', occasion: 'birthday', rating: 4.6, reviews: 77, stock: 35, description: 'Everything a tech lover craves: wireless charging pad, cable organiser, desk gadgets, and premium earbuds — all in a sleek black box.', images: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=600&auto=format&fit=crop'], tags: ['tech', 'gadgets', 'modern'], isNew: true },
  { id: 'p10', title: 'Artisan Belgian Chocolate Tower', price: 1299, originalPrice: 1599, category: 'her', occasion: 'birthday', rating: 4.8, reviews: 230, stock: 60, description: 'A towering selection of single-origin dark, milk and white chocolates from Belgian artisans. A guaranteed crowd pleaser.', images: ['https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=600&auto=format&fit=crop'], tags: ['chocolate', 'artisan', 'sweet'], isNew: false },
  { id: 'p11', title: 'Personalised Photo Frame Set', price: 1199, originalPrice: null, category: 'her', occasion: 'anniversary', rating: 4.6, reviews: 142, stock: 55, description: 'A set of three premium wooden photo frames with custom engraving. Preserve your most cherished memories in style.', images: ['https://images.unsplash.com/photo-1513519245088-0e12902e35ca?q=80&w=600&auto=format&fit=crop'], tags: ['personalised', 'photo', 'keepsake'], isNew: false },
  { id: 'p12', title: 'Aromatic Candle Collection', price: 999, originalPrice: null, category: 'her', occasion: 'housewarming', rating: 4.7, reviews: 198, stock: 70, description: 'A collection of 6 hand-poured soy wax candles in fragrances like lavender, vanilla, sandalwood, and jasmine. Each burns for 40+ hours.', images: ['https://images.unsplash.com/photo-1602607742444-f6b9eec0dd5e?q=80&w=600&auto=format&fit=crop'], tags: ['candles', 'aromatic', 'home'], isNew: true },
  { id: 'p13', title: "Men's Grooming Luxury Kit", price: 2499, originalPrice: 2999, category: 'him', occasion: 'birthday', rating: 4.5, reviews: 86, stock: 40, description: 'Complete grooming essentials: beard oil, face wash, moisturiser, and aftershave balm from premium organic brands, presented in a leather dopp kit.', images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=600&auto=format&fit=crop'], tags: ['grooming', 'mens', 'luxury'], isNew: false },
  { id: 'p14', title: 'Handwoven Pashmina Shawl', price: 3999, originalPrice: null, category: 'her', occasion: 'festival', rating: 4.9, reviews: 67, stock: 18, description: 'An authentic Kashmiri pashmina shawl handwoven by master artisans. Soft, warm, and timelessly elegant — a gift of true luxury.', images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=600&auto=format&fit=crop'], tags: ['pashmina', 'handwoven', 'luxury'], isNew: true },
  { id: 'p15', title: 'Premium Coffee Brewing Set', price: 1799, originalPrice: null, category: 'him', occasion: 'housewarming', rating: 4.7, reviews: 103, stock: 35, description: 'A curated pour-over coffee set including a ceramic dripper, gooseneck kettle, hand grinder, and 250g of single-origin beans from Coorg.', images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=600&auto=format&fit=crop'], tags: ['coffee', 'brewing', 'artisan'], isNew: false },
  { id: 'p16', title: 'Silk Saree Gift Box', price: 4999, originalPrice: 5999, category: 'her', occasion: 'wedding', rating: 4.8, reviews: 54, stock: 12, description: 'A luxurious Banarasi silk saree presented in a custom embroidered gift box with matching blouse fabric and a handwritten blessing card.', images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=600&auto=format&fit=crop'], tags: ['silk', 'saree', 'wedding'], isNew: true },
  { id: 'p17', title: 'Personalised Wallet & Belt Set', price: 2899, originalPrice: null, category: 'him', occasion: 'corporate', rating: 4.6, reviews: 91, stock: 28, description: 'Italian leather wallet and belt set with custom monogram initials. Presented in a premium magnetic-close box — ideal for corporate gifting.', images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=600&auto=format&fit=crop'], tags: ['wallet', 'leather', 'personalised'], isNew: false },
  { id: 'p18', title: 'Organic Tea Collection Box', price: 1199, originalPrice: null, category: 'her', occasion: 'festival', rating: 4.7, reviews: 176, stock: 65, description: 'A curated box of 8 organic teas — Darjeeling first flush, Assam gold, chamomile, green, and more. Sourced directly from Indian estates.', images: ['https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=600&auto=format&fit=crop'], tags: ['tea', 'organic', 'collection'], isNew: false },
  { id: 'p19', title: 'Bluetooth Speaker Gift Pack', price: 3299, originalPrice: 3999, category: 'him', occasion: 'birthday', rating: 4.5, reviews: 63, stock: 30, description: 'Premium portable Bluetooth speaker with rich bass, 12-hour battery life, and waterproof design. Comes gift-wrapped with premium earbuds.', images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=600&auto=format&fit=crop'], tags: ['speaker', 'tech', 'music'], isNew: true },
  { id: 'p20', title: 'Baby Welcome Hamper', price: 2199, originalPrice: null, category: 'her', occasion: 'birthday', rating: 4.8, reviews: 87, stock: 32, description: 'Celebrate the arrival of a little one with organic cotton onesies, a plush toy, baby blanket, and milestone cards — all in a keepsake basket.', images: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?q=80&w=600&auto=format&fit=crop'], tags: ['baby', 'newborn', 'hamper'], isNew: false },
  { id: 'p21', title: 'Diwali Festive Dry Fruit Box', price: 2499, originalPrice: 2999, category: 'her', occasion: 'festival', rating: 4.8, reviews: 188, stock: 80, description: 'A premium assortment of almonds, cashews, pistachios, and figs presented in a handcrafted brass-finish box with a festive ribbon.', images: ['https://images.unsplash.com/photo-1606312619070-d48b4c652a52?q=80&w=600&auto=format&fit=crop'], tags: ['diwali', 'dryfruit', 'festival'], isNew: true },
  { id: 'p22', title: 'Luxury Perfume Gift Set', price: 3699, originalPrice: null, category: 'him', occasion: 'anniversary', rating: 4.7, reviews: 72, stock: 22, description: 'A trio of premium eau de parfum miniatures (woody, citrus, and oriental notes) presented in a velvet-lined collector box.', images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=600&auto=format&fit=crop'], tags: ['perfume', 'fragrance', 'luxury'], isNew: false },
  { id: 'p23', title: 'Copper Pooja Thali Set', price: 1599, originalPrice: null, category: 'her', occasion: 'festival', rating: 4.6, reviews: 94, stock: 45, description: 'A beautifully crafted copper pooja thali with diya, incense holder, bell, and kumkum container. Perfect for Diwali and housewarming ceremonies.', images: ['https://images.unsplash.com/photo-1574169208507-84376144848b?q=80&w=600&auto=format&fit=crop'], tags: ['pooja', 'copper', 'traditional'], isNew: false },
  { id: 'p24', title: 'Corporate Welcome Kit', price: 1999, originalPrice: null, category: 'him', occasion: 'corporate', rating: 4.5, reviews: 54, stock: 45, description: 'A sophisticated desk set: matte-black stationery, marble bookends, branded ceramic mug, and a premium notebook. Perfect for new hires or promotions.', images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=600&auto=format&fit=crop'], tags: ['corporate', 'desk', 'professional'], isNew: false },
];

async function seed() {
  for (const p of MOCK_PRODUCTS) {
    const res = await fetch('http://localhost:3001/api/products', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(p)
    });
    console.log('Seeded:', p.id, p.title, res.status);
  }
  console.log(`\nDone! Seeded ${MOCK_PRODUCTS.length} products.`);
}
seed();
